version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    depends_on:
      - php
    restart: always
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "db"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
volumes:
  mysqldata: {}
